### ISSUE TITLE
Z39.50 Repeating attribute results in an error

### ISSUE THREAD

**Issue by natlibfi-arlehiko** [indexdata/yazproxy#15]
The following Z39.50 query results in an error even though defined in attribute mapping:
```
@attr 4=1,2 foo
```
The error:
`[113] Unsupported attribute type -- v2 addinfo '4`

Should be supported:
https://www.loc.gov/z3950/agency/attrarch/attrarch.html (`3.1.5.1 Mechanism for Repeating Attribute`)

In configuration we have the following settings for `4`:
`<attribute type="4" value="1,2"/>`
`<attribute type="4" value="*" error="118"/>`
And catch-all:
`<attribute type="*" value="*" error="113"/>`

Commenting out the catch-all line makes the query work.

**Comment by adamdickmeiss** [comment]
Query `@attr 4=1,2 foo` will map to value "1,2" -- that's a string, not two numeric values. In order to send those two values, you'd have to specify `@attr 4=1 @attr 4=2 foo`. However, you shouldn't do that. Send only one value (choose either 4=1 or 4=2).

Refer to Attributes section of:
https://www.loc.gov/z3950/agency/bib1.html

> Within an attribute list, multiple instances of a given type of
> attribute element are undefined and discouraged.  Use of version 3
> semantic actions is encouraged.
